# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DataFetch' do
pod 'Alamofire', '3.1.4'
end

target 'DataFetchTests' do

end

target 'DataFetchUITests' do

end

